-- MySQL Script generated by MySQL Workbench
-- Thu Aug 25 09:59:05 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema opixido_films
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema opixido_films
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `opixido_films` DEFAULT CHARACTER SET utf8 ;
USE `opixido_films` ;

-- -----------------------------------------------------
-- Table `opixido_films`.`personne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opixido_films`.`personne` (
  `p_id` INT NOT NULL AUTO_INCREMENT,
  `p_nom` VARCHAR(120) NULL,
  `p_role` VARCHAR(45) NULL,
  PRIMARY KEY (`p_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opixido_films`.`film`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opixido_films`.`film` (
  `f_id` INT NOT NULL AUTO_INCREMENT,
  `f_titre` VARCHAR(255) NULL,
  `f_annee` INT NULL,
  `f_desc` LONGTEXT NULL,
  `f_affiche` VARCHAR(255) NULL,
  PRIMARY KEY (`f_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opixido_films`.`film_has_personne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opixido_films`.`film_has_personne` (
  `film_f_id` INT NOT NULL,
  `personne_p_id` INT NOT NULL,
  PRIMARY KEY (`film_f_id`, `personne_p_id`),
  INDEX `fk_film_has_personne_personne1_idx` (`personne_p_id` ASC),
  INDEX `fk_film_has_personne_film_idx` (`film_f_id` ASC),
  CONSTRAINT `fk_film_has_personne_film`
    FOREIGN KEY (`film_f_id`)
    REFERENCES `opixido_films`.`film` (`f_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_film_has_personne_personne1`
    FOREIGN KEY (`personne_p_id`)
    REFERENCES `opixido_films`.`personne` (`p_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
