<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Opixido films</title>
    <meta name="description" content="Opixido films">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style/style.css">
    <script src="https://kit.fontawesome.com/597204d2aa.js" crossorigin="anonymous"></script>
</head>
<body>
    <header class="Header">
            <h1 class="Header-titre">
                <a href="index.php"class="Header-titre-lien">CINEFILM</a>
            </h1>
    </header>
    <main class="Main">
        <?php include  __DIR__ .'/../templates/' . $template . '.phtml'; ?>
    </main>

    <footer class="Footer">
    <div class="Footer-content">
        <a href="#">politiques privées</a>
        <a href="#">cookies</a>
        <div class="Footer-content-sns">
            <a href="#"><i class="fa-brands fa-twitter"></i></a>
            <a href="#"><i class="fa-brands fa-instagram"></i></a>
            <a href="#"><i class="fa-brands fa-youtube"></i></a>
            <a href="#"><i class="fa-brands fa-tiktok"></i></a>
        </div>
    </footer>
</body>
</html>